# Generated by Django 5.1.7 on 2025-03-20 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='basketList',
            field=models.ManyToManyField(blank=True, to='backend_api.book'),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='userId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
