# Generated by Django 5.1.7 on 2025-03-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_alter_book_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('userName', models.CharField(max_length=100)),
                ('mark', models.IntegerField()),
                ('value', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='reviews',
            field=models.ManyToManyField(to='backend_api.bookreview'),
        ),
    ]
