# Generated by Django 5.1.7 on 2025-03-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0004_bookreview_book_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='backend_api.bookreview'),
        ),
    ]
