# Generated by Django 5.1.7 on 2025-03-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0004_basket_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='quantity',
        ),
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
