# Generated by Django 5.1.7 on 2025-03-26 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('backend_api', '0005_remove_basket_quantity_book_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='backend_api_user_set', to='auth.permission'),
        ),
    ]
