# Generated by Django 5.1.7 on 2025-03-28 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0007_alreadyview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alreadyview',
            old_name='userId',
            new_name='view_userId',
        ),
    ]
